# Generated by Django 5.1.7 on 2025-04-29 15:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0004_companysignature_companystamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Customer's full name", max_length=255)),
                ('company_name', models.CharField(blank=True, help_text="Customer's company name", max_length=255, null=True)),
                ('phone_number', models.CharField(blank=True, help_text="Customer's phone number", max_length=15, null=True)),
                ('email', models.EmailField(blank=True, help_text="Customer's email address", max_length=254, null=True)),
                ('gst_number', models.CharField(blank=True, help_text="Customer's GST number", max_length=15, null=True)),
                ('created_by', models.CharField(blank=True, help_text='Name of the company proprietor who created this customer', max_length=255, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when this customer was created')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='companies.company')),
            ],
        ),
    ]
