# Generated by Django 5.1.7 on 2025-04-30 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the address (e.g., 'Main Office', 'Warehouse')", max_length=255)),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('pincode', models.CharField(help_text='Postal/ZIP code', max_length=10)),
                ('city', models.CharField(help_text='City/Town', max_length=100)),
                ('state', models.CharField(help_text='State/Province/Region', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('customer', models.OneToOneField(help_text='Customer this billing address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the address (e.g., 'Main Office', 'Warehouse')", max_length=255)),
                ('address_line_1', models.CharField(help_text='Street address, P.O. box, company name', max_length=255)),
                ('address_line_2', models.CharField(blank=True, help_text='Apartment, suite, unit, building, floor, etc.', max_length=255, null=True)),
                ('pincode', models.CharField(help_text='Postal/ZIP code', max_length=10)),
                ('city', models.CharField(help_text='City/Town', max_length=100)),
                ('state', models.CharField(help_text='State/Province/Region', max_length=100)),
                ('country', models.CharField(default='India', help_text='Country', max_length=100)),
                ('is_default', models.BooleanField(default=False, help_text='Whether this is the default shipping address for the customer')),
                ('customer', models.ForeignKey(help_text='Customer this shipping address belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='shipping_addresses', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Shipping Address',
                'verbose_name_plural': 'Shipping Addresses',
                'ordering': ['-is_default', 'name'],
            },
        ),
    ]
