# Generated by Django 5.1.7 on 2025-05-02 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('companies', '0006_alter_additionalfield_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('selling_price_with_tax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percent', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True)),
                ('unit', models.CharField(choices=[('oth', 'Others'), ('pcs', 'Pieces'), ('nos', 'Numbers'), ('kgs', 'Kilogram'), ('unt', 'Unit'), ('box', 'Box'), ('pac', 'Packs'), ('each', 'Each')], max_length=10)),
                ('hsn_sac', models.CharField(blank=True, max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.category')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='companies.company')),
            ],
        ),
    ]
