# Generated by Django 5.1.7 on 2025-04-16 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySignature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('signature_image', models.ImageField(upload_to='company_signatures/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='companies.company')),
            ],
        ),
        migrations.CreateModel(
            name='CompanyStamp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('stamp_image', models.ImageField(upload_to='company_stamps/')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stamps', to='companies.company')),
            ],
        ),
    ]
