# Generated by Django 5.1.7 on 2025-05-01 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0005_additionalfield'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalfield',
            name='value',
            field=models.TextField(blank=True),
        ),
    ]
